### ISSUE TITLE
Deps should be installed on docker build

### ISSUE THREAD

**Issue by eduard93** [danoleg/cryptocurrency-rate-forecasting#1]
First thing I see in the https://github.com/danoleg/cryptocurrency-rate-forecasting/blob/main/jupyter-notebooks/bitcoin-rate-forecasting.ipynb

```
!apt-get update
!apt-get install gcc
!apt-get install -y tdsodbc unixodbc-dev
!apt install unixodbc-bin -y
!apt-get clean
```

and

```
!pip install pyodbc
!pip install pandas
!rm /etc/odbcinst.ini
!rm /etc/odbc.ini
!ln -s /tf/odbcinst.ini /etc/odbcinst.ini
!ln -s /tf/odbc.ini /etc/odbc.ini
!cat /tf/odbcinst.ini
!cat /tf/odbc.ini
!odbcinst -j
```

This should be done during the `docker build` stage not in a notebook.

**Comment by danoleg** [comment]
I agree, it will be better. I will add this correction in next release.

**Comment by danoleg** [comment]
All config commands moved to Dockerfile
